name: Build Kristine

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-android-app:
    name: Build Android app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Run gradle assemble task
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x gradlew 
          ./gradlew assemble --stacktrace

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Apk distribution
          path: ./composeApp/build/outputs/apk/debug/*
  build-linux-app:
    name: Build Linux app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Run gradle package task
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x gradlew 
          ./gradlew packageDistributionForCurrentOS --no-daemon

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Deb distribution
          path: ./composeApp/build/compose/binaries/main/deb/*
  build-windows-app:
    name: Build Windows app
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v3

      - name: Gradle Build
        uses: gradle/gradle-build-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: packageDistributionForCurrentOS --no-daemon

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Exe distribution
          path: ./composeApp/build/compose/binaries/main/exe/*
